alias sar="sudo service apache2 restart"
alias sv="sudo vim"
alias py="python3"
alias ipy="python3 -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"
alias pipin="python3 -m pip install --user"
alias pipun="python3 -m pip uninstall --user"
