#!/bin/bash

sudo apt-get install python3 python3-dev python-dev
sudo apt-get install gfortran libopenblas-dev liblapack-dev
# Dependencies for matplotlib
sudo apt-get install libpng-dev libfreetype6-dev

# Install commonly used python libraries
sudo pip3 install ipython numpy scipy matplotlib pandas

if [ ! -f $HOME/.ipython/profile_default/startup/ipython_startup.py ]
then
    echo ipython_startup does not exist in $HOME/.ipython/profile_default/startup... symlinking it now
    sudo ln -s $PWD/ipython_startup.py $HOME/.ipython/profile_default/startup/ipython_startup.py
else
    echo ipython_startup already exists in $HOME/.ipython/profile_default/startup
fi
