#!/bin/bash

sudo apt-get -yq install python3 python3-dev python3-pip
sudo apt-get -yq install gfortran libopenblas-dev liblapack-dev
# Dependencies for matplotlib
sudo apt-get -yq install libpng-dev libfreetype6-dev

# Install commonly used python libraries
python3 -m pip install --user ipython numpy scipy matplotlib pandas tensorflow
